# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b27477bef44d9db34118171f1a9258f59f1a6d09595c5d614864b7340febfa9a7408c83805174f9750a5af1d969ad703382e76893414f4d434dfacf618e89609

test:
  secret_key_base: 1b06c57d7aefa90a88ce6cdbddcf92a797d3b931940ef7d5eac1399285a9fa659dc0340049f4ab3e4cdb38b54fcc7cdd704f22ea55f1f68515575a1fc3196666

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
